language: ruby

arch:
  - amd64
  - arm64

rvm:
  - 2.4
  - 2.7
  - 3.1.2

os:
  - linux
  - osx

services: docker

jobs:
  exclude:
    # does not work - rvm cannot install ruby
    - rvm: 3.1.2
      arch: arm64

before_install:
  - gem install bundler:2.2.15
#  - docker pull ghcr.io/eugenmayer/unison:2.52.1-4.12.0
#  - docker pull eugenmayer/rsync

script: bundle exec rspec --format=documentation
