language: ruby

rvm:
  # Removed those to since bundler is to old on those 2
  - 2.4
  - 2.7

#os: osx

services: docker

before_install:
  - gem install bundler:2.2.15
  - docker pull eugenmayer/unison:2.51.3-4.12.0-AMD64
  - docker pull eugenmayer/rsync

script: bundle exec rspec --format=documentation
